{
 "title": "OTLP HTTP Services",
 "tags": [
  "otlp",
  "metrics",
  "traces",
  "logs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "服务名",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "instance",
    "label": "服务实例",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"$job\"},instance)"
    }
   },
   {
    "name": "http_route",
    "label": "API URL",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{instance=\"$instance\"},http_route)"
    }
   },
   {
    "name": "predictive_interval",
    "label": "预期区间",
    "query": "1m,3m,5m,10m,30m,1h,2h,6h,12h,1d,2d,3d,1w"
   },
   {
    "name": "predictive_offset",
    "label": "预期偏移量",
    "query": "5s,10s,30s,1m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "每个服务的性能指标",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route) (increase(http_server_request_duration_seconds_sum{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval])) / sum by(http_route) (increase(http_server_request_duration_seconds_count{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (rate(http_server_request_duration_seconds_bucket{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route) (increase(http_server_request_duration_seconds_count{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(http_route) (http_server_request_duration_seconds_count{instance=\"$instance\", http_response_status_code=~\"2.*\"}) / sum by(http_route) (http_server_request_duration_seconds_count{instance=\"$instance\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "过去 $__interval 每个端点的TPS，及其 $predictive_interval 后偏移 $predictive_offset 的预估值",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "double_exponential_smoothing(avg(sum by(http_route) (rate(http_server_request_duration_seconds_count{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval])))[$predictive_interval:] offset $predictive_offset, 0.5, 0.5) * 0.5",
     "legendFormat": "预估值"
    }
   ]
  },
  {
   "title": "每 $__interval 各端点的P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(http_route, le) (rate(http_server_request_duration_seconds_bucket{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "各端点的当前P95",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(http_route, le) (rate(http_server_request_duration_seconds_bucket{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Mesh",
   "type": "nodeGraph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "limit": 20, "serviceMapQuery": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "当前响应时间分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_server_request_duration_seconds_bucket{instance=\"$instance\", http_route=~\"$http_route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "所有的Spring Boot应用日志",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{service_instance_id=\"$instance\"} | line_format `[1m{{if .level }}{{alignRight 5 .level}}{{else if .severity_text}}{{alignRight 5 .severity_text}}{{end}}\u001b[0m \u001b[90m[{{alignLeft 20 .service_instance_id}}]\u001b[0m \u001b[36m{{if .scope_name }}{{.scope_name}}{{end}}\u001b[0m {{__line__}} {{if .trace_id}} \u001btrace_id: [{{.trace_id}}]{{end}} {{if .span_id}} \u001bspan_id: [{{.span_id}}]{{end}} {{if .flags}} \u001btrace_flags: [{{.flags}}]{{end}}`"
    }
   ]
  }
 ]
}